# Generated by Django 2.1.2 on 2019-02-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='picc.jpg', upload_to='profile_pics'),
        ),
    ]
