# Generated by Django 2.1.2 on 2019-02-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190202_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='picc.jpg', upload_to='profile_pics'),
        ),
    ]
