# Generated by Django 2.1.2 on 2019-02-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190202_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='coat_of_arm.jpg', upload_to='profile_pics'),
        ),
    ]
