# Generated by Django 2.1.2 on 2019-03-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
