# Generated by Django 2.1.2 on 2019-03-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
